version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./laravel-subapp:/var/www
    networks:
      - mainnetwork
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./laravel-subapp:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - mainnetwork
  db:
    container_name: db
    image: mysql:8
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: subapp
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - mainnetwork
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8078:80"
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=
    networks:
      - mainnetwork
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    networks:
      - mainnetwork
      
networks:
  mainnetwork:
    driver: bridge